import sys

filepath = 'backend-go/services/llm.go'
with open(filepath, 'rb') as f:
    content = f.read()

old_section = (
    b'\tlog.Printf("[LLM] Sending request to %s (model: %s)", apiURL, model)\r\n'
    b'\tresp, err := llmHttpClient.Do(req)\r\n'
    b'\tif err != nil {\r\n'
    b'\t\treturn LLMResult{}, err\r\n'
    b'\t}\r\n'
    b'\tdefer resp.Body.Close()\r\n'
    b'\r\n'
    b'\tif resp.StatusCode >= 400 {\r\n'
    b'\t\tbody, _ := io.ReadAll(resp.Body)\r\n'
    b'\t\treturn LLMResult{}, fmt.Errorf("LLM request to %s failed (%d): %s", apiURL, resp.StatusCode, string(body))\r\n'
    b'\t}\r\n'
    b'\r\n'
    b'\tvar data struct {\r\n'
    b'\t\tChoices []struct {\r\n'
    b'\t\t\tMessage struct {\r\n'
    b'\t\t\t\tContent string `json:"content"`\r\n'
    b'\t\t\t\tReasoningContent string `json:"reasoning_content"`\r\n'
    b'\t\t\t\tReasoning string `json:"reasoning"`\r\n'
    b'\t\t\t} `json:"message"`\r\n'
    b'\t\t} `json:"choices"`\r\n'
    b'\t\tUsage struct {\r\n'
    b'\t\t\tPromptTokens int `json:"prompt_tokens"`\r\n'
    b'\t\t\tCompletionTokens int `json:"completion_tokens"`\r\n'
    b'\t\t\tTotalTokens int `json:"total_tokens"`\r\n'
    b'\t\t} `json:"usage"`\r\n'
    b'\t}\r\n'
    b'\tif err := json.NewDecoder(resp.Body).Decode(&data); err != nil {\r\n'
    b'\t\treturn LLMResult{}, err\r\n'
    b'\t}\r\n'
    b'\tif len(data.Choices) == 0 {\r\n'
    b'\t\treturn LLMResult{}, fmt.Errorf("LLM response contained no choices")\r\n'
    b'\t}\r\n'
    b'\t// Use content field, fall back to reasoning_content then reasoning for reasoning models\r\n'
    b'\tresultContent := strings.TrimSpace(data.Choices[0].Message.Content)\r\n'
    b'\tif resultContent == "" {\r\n'
    b'\t\tresultContent = strings.TrimSpace(data.Choices[0].Message.ReasoningContent)\r\n'
    b'\t}\r\n'
    b'\tif resultContent == "" {\r\n'
    b'\t\tresultContent = strings.TrimSpace(data.Choices[0].Message.Reasoning)\r\n'
    b'\t}\r\n'
    b'\tif resultContent == "" {\r\n'
    b'\t\treturn LLMResult{}, fmt.Errorf("LLM returned empty content (finish_reason may be length)")\r\n'
    b'\t}\r\n'
    b'\treturn LLMResult{\r\n'
    b'\t\tContent: resultContent,\r\n'
    b'\t\tLatencyMs: float64(time.Since(start).Milliseconds()),\r\n'
    b'\t\tUsage: &LLMUsage{\r\n'
    b'\t\t\tPromptTokens: data.Usage.PromptTokens,\r\n'
    b'\t\t\tCompletionTokens: data.Usage.CompletionTokens,\r\n'
    b'\t\t\tTotalTokens: data.Usage.TotalTokens,\r\n'
    b'\t\t},\r\n'
    b'\t}, nil\r\n'
    b'}'
)

new_section = (
    b'\tlog.Printf("[LLM] Sending request to %s (model: %s)", apiURL, model)\r\n'
    b'\r\n'
    b'\t// Retry logic for LM Studio "Model unloaded" errors (model needs time to reload)\r\n'
    b'\tmaxRetries := 0\r\n'
    b'\tisLMStudio := strings.Contains(apiURL, "localhost:1234")\r\n'
    b'\tif isLMStudio {\r\n'
    b'\t\tmaxRetries = 3\r\n'
    b'\t}\r\n'
    b'\r\n'
    b'\tvar lastErr error\r\n'
    b'\tfor attempt := 0; attempt <= maxRetries; attempt++ {\r\n'
    b'\t\tif attempt > 0 {\r\n'
    b'\t\t\tlog.Printf("[LLM] Retrying LM Studio request (attempt %d/%d) after model reload delay", attempt+1, maxRetries+1)\r\n'
    b'\t\t\ttime.Sleep(time.Duration(attempt) * 3 * time.Second)\r\n'
    b'\t\t}\r\n'
    b'\r\n'
    b'\t\t// Rebuild request for each attempt (body is consumed by Do)\r\n'
    b'\t\tretryReq, err := http.NewRequest(http.MethodPost, apiURL, bytes.NewReader(requestBody))\r\n'
    b'\t\tif err != nil {\r\n'
    b'\t\t\treturn LLMResult{}, err\r\n'
    b'\t\t}\r\n'
    b'\t\tretryReq.Header.Set("Authorization", "Bearer "+apiKey)\r\n'
    b'\t\tretryReq.Header.Set("Content-Type", "application/json")\r\n'
    b'\t\tif strings.Contains(apiURL, "openrouter.ai") {\r\n'
    b'\t\t\tretryReq.Header.Set("HTTP-Referer", "https://jules-autopilot.render.com")\r\n'
    b'\t\t\tretryReq.Header.Set("X-Title", "Jules Autopilot")\r\n'
    b'\t\t}\r\n'
    b'\r\n'
    b'\t\tresp, err := llmHttpClient.Do(retryReq)\r\n'
    b'\t\tif err != nil {\r\n'
    b'\t\t\tlastErr = err\r\n'
    b'\t\t\tcontinue\r\n'
    b'\t\t}\r\n'
    b'\r\n'
    b'\t\tif resp.StatusCode >= 400 {\r\n'
    b'\t\t\tbody, _ := io.ReadAll(resp.Body)\r\n'
    b'\t\t\tresp.Body.Close()\r\n'
    b'\t\t\terrBody := string(body)\r\n'
    b'\r\n'
    b'\t\t\t// LM Studio "Model unloaded" - retry after reload\r\n'
    b'\t\t\tif isLMStudio && attempt < maxRetries && (strings.Contains(errBody, "Model unloaded") || strings.Contains(errBody, "model not found") || strings.Contains(errBody, "not loaded")) {\r\n'
    b'\t\t\t\tlog.Printf("[LLM] LM Studio model not loaded (attempt %d/%d): %s", attempt+1, maxRetries+1, errBody[:min(len(errBody), 100)])\r\n'
    b'\t\t\t\tlastErr = fmt.Errorf("LLM request to %s failed (%d): %s", apiURL, resp.StatusCode, errBody)\r\n'
    b'\t\t\t\tcontinue\r\n'
    b'\t\t\t}\r\n'
    b'\r\n'
    b'\t\t\treturn LLMResult{}, fmt.Errorf("LLM request to %s failed (%d): %s", apiURL, resp.StatusCode, errBody)\r\n'
    b'\t\t}\r\n'
    b'\r\n'
    b'\t\t// Success - decode response\r\n'
    b'\t\tvar data struct {\r\n'
    b'\t\t\tChoices []struct {\r\n'
    b'\t\t\t\tMessage struct {\r\n'
    b'\t\t\t\t\tContent string `json:"content"`\r\n'
    b'\t\t\t\t\tReasoningContent string `json:"reasoning_content"`\r\n'
    b'\t\t\t\t\tReasoning string `json:"reasoning"`\r\n'
    b'\t\t\t\t} `json:"message"`\r\n'
    b'\t\t\t} `json:"choices"`\r\n'
    b'\t\t\tUsage struct {\r\n'
    b'\t\t\t\tPromptTokens int `json:"prompt_tokens"`\r\n'
    b'\t\t\t\tCompletionTokens int `json:"completion_tokens"`\r\n'
    b'\t\t\t\tTotalTokens int `json:"total_tokens"`\r\n'
    b'\t\t\t} `json:"usage"`\r\n'
    b'\t\t}\r\n'
    b'\t\tif err := json.NewDecoder(resp.Body).Decode(&data); err != nil {\r\n'
    b'\t\t\tresp.Body.Close()\r\n'
    b'\t\t\treturn LLMResult{}, err\r\n'
    b'\t\t}\r\n'
    b'\t\tresp.Body.Close()\r\n'
    b'\t\tif len(data.Choices) == 0 {\r\n'
    b'\t\t\treturn LLMResult{}, fmt.Errorf("LLM response contained no choices")\r\n'
    b'\t\t}\r\n'
    b'\t\t// Use content field, fall back to reasoning_content then reasoning for reasoning models\r\n'
    b'\t\tresultContent := strings.TrimSpace(data.Choices[0].Message.Content)\r\n'
    b'\t\tif resultContent == "" {\r\n'
    b'\t\t\tresultContent = strings.TrimSpace(data.Choices[0].Message.ReasoningContent)\r\n'
    b'\t\t}\r\n'
    b'\t\tif resultContent == "" {\r\n'
    b'\t\t\tresultContent = strings.TrimSpace(data.Choices[0].Message.Reasoning)\r\n'
    b'\t\t}\r\n'
    b'\t\tif resultContent == "" {\r\n'
    b'\t\t\treturn LLMResult{}, fmt.Errorf("LLM returned empty content (finish_reason may be length)")\r\n'
    b'\t\t}\r\n'
    b'\t\treturn LLMResult{\r\n'
    b'\t\t\tContent: resultContent,\r\n'
    b'\t\tLatencyMs: float64(time.Since(start).Milliseconds()),\r\n'
    b'\t\t\tUsage: &LLMUsage{\r\n'
    b'\t\t\t\tPromptTokens: data.Usage.PromptTokens,\r\n'
    b'\t\t\t\tCompletionTokens: data.Usage.CompletionTokens,\r\n'
    b'\t\t\t\tTotalTokens: data.Usage.TotalTokens,\r\n'
    b'\t\t\t},\r\n'
    b'\t\t}, nil\r\n'
    b'\t}\r\n'
    b'\r\n'
    b'\treturn LLMResult{}, fmt.Errorf("LLM request to %s failed after %d attempts: %w", apiURL, maxRetries+1, lastErr)\r\n'
    b'}'
)

if old_section in content:
    content = content.replace(old_section, new_section, 1)
    print("SUCCESS: Replaced LLM request section with retry logic")
else:
    print("ERROR: Pattern not found!")
    idx = content.find(b'Sending request to %s')
    if idx >= 0:
        print(f"Found 'Sending request' at offset {idx}")
        print(repr(content[idx-30:idx+200]))
    sys.exit(1)

with open(filepath, 'wb') as f:
    f.write(content)
