export interface HelpTopic {
  title: string;
  summary: string;
  docSlug?: string;
}

export const HELP_CONTENT: Record<string, HelpTopic> = {
  "default": {
    title: "Jules Help",
    summary: "Welcome to Jules. Click on specific areas or use the documentation to learn more.",
    docSlug: "intro"
  },
  "sessions": {
    title: "Session Board",
    summary: "The Session Board gives you a high-level view of all your AI sessions. Each card represents a distinct task or conversation. You can drag and drop cards to organize them.",
    docSlug: "intro"
  },
  "board": {
    title: "Session Board",
    summary: "The Session Board gives you a high-level view of all your AI sessions. Each card represents a distinct task or conversation. You can drag and drop cards to organize them.",
    docSlug: "intro"
  },
  "activity-feed": {
    title: "Activity Feed",
    summary: "The Activity Feed shows a real-time stream of everything the agent is doing. This includes 'thoughts' (internal reasoning), tool calls (terminal commands, file edits), and system messages.",
    docSlug: "agents"
  },
  "terminal": {
    title: "Integrated Terminal",
    summary: "The integrated terminal allows you to interact directly with the underlying system. You can run commands, check file status, and monitor long-running processes.",
    docSlug: "terminal"
  },
  "artifacts": {
    title: "Artifact Browser",
    summary: "Artifacts are files or outputs generated by the agent. This browser lets you view code diffs, images, and other resources created during the session.",
    docSlug: "intro"
  },
  "submodules": {
    title: "Submodule Dashboard",
    summary: "View the status of all connected submodules and external tools. Check versions, branches, and synchronization status.",
    docSlug: "submodules"
  },
  "kanban": {
    title: "Kanban Board",
    summary: "Visualize your sessions by status (Active, Paused, Completed). Useful for managing multiple concurrent tasks.",
    docSlug: "intro"
  },
  "analytics": {
    title: "Analytics Dashboard",
    summary: "Track token usage, costs, and agent performance metrics over time.",
    docSlug: "intro"
  },
  "debates": {
    title: "Council Debates",
    summary: "Monitor multi-agent debates where different personas discuss the best approach before executing actions.",
    docSlug: "agents"
  },
  "templates": {
    title: "Session Templates",
    summary: "Manage and use templates to quickly start new sessions with predefined prompts and configurations.",
    docSlug: "intro"
  }
};
