package services

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"runtime"
	"sync"
	"time"

	"github.com/getlantern/systray"
	"github.com/jules-autopilot/backend/db"
	"github.com/jules-autopilot/backend/models"
)

var trayOnce sync.Once

// embeddedTrayIcon is a 32x32 blue triangle PNG generated at build time.
// Generated by a Python script and embedded here to avoid external files.
var embeddedTrayIcon = []byte{
	0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D,
	0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x20,
	0x08, 0x06, 0x00, 0x00, 0x00, 0x73, 0x7A, 0x7A, 0xF4, 0x00, 0x00, 0x00,
	0x79, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9C, 0xE5, 0xCE, 0x49, 0x0A, 0xC0,
	0x20, 0x10, 0x05, 0x51, 0x8F, 0x9D, 0x83, 0xE6, 0x3E, 0x89, 0x59, 0x18,
	0x5C, 0x88, 0xD8, 0x63, 0x21, 0x36, 0xFC, 0x6D, 0xD7, 0x2B, 0xC5, 0x7A,
	0xD7, 0xFD, 0x98, 0x7F, 0xEC, 0x0B, 0xF8, 0xE2, 0x6D, 0xE7, 0x01, 0xFA,
	0x38, 0x82, 0x40, 0x01, 0xA3, 0x78, 0x2A, 0x02, 0x05, 0xCC, 0xE2, 0x29,
	0x08, 0x14, 0xB0, 0x12, 0x0F, 0x45, 0xA0, 0x00, 0x49, 0x3C, 0x04, 0x81,
	0x02, 0x34, 0x71, 0x57, 0x04, 0x0A, 0xB0, 0xC4, 0x5D, 0x10, 0x28, 0xC0,
	0x23, 0x6E, 0x42, 0xA0, 0x00, 0xCF, 0xB8, 0x0A, 0x81, 0x02, 0x22, 0xE2,
	0x22, 0x04, 0x0A, 0x88, 0x8C, 0x2F, 0x21, 0x50, 0x40, 0x46, 0x7C, 0x8A,
	0x40, 0x01, 0x99, 0xF1, 0x21, 0x02, 0x05, 0x10, 0xF1, 0x1F, 0x41, 0xC6,
	0xEB, 0x5E, 0xB0, 0x7B, 0x98, 0x88, 0x15, 0x0A, 0x40, 0x62, 0x00, 0x00,
	0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
}

// StartTray initializes the system tray icon in-process using systray library.
func StartTray() {
	trayOnce.Do(func() {
		log.Println("[Tray] Starting in-process system tray icon...")
		go func() {
			runtime.LockOSThread()
			defer runtime.UnlockOSThread()
			defer func() {
				if r := recover(); r != nil {
					log.Printf("[Tray] Panic: %v", r)
				}
			}()
			systray.Run(onTrayReady, onTrayExit)
		}()
	})
}

func onTrayReady() {
	systray.SetIcon(embeddedTrayIcon)
	systray.SetTitle("Jules Autopilot")
	systray.SetTooltip(getTrayTooltip())

	mDashboard := systray.AddMenuItem("Dashboard", "Open dashboard")
	mStatus := systray.AddMenuItem("Status", "Service status")
	systray.AddSeparator()
	mRestartDaemon := systray.AddMenuItem("Restart Daemon", "Restart the monitoring daemon")
	mRestartWorker := systray.AddMenuItem("Restart Worker", "Restart the queue worker")
	systray.AddSeparator()
	mQuit := systray.AddMenuItem("Quit", "Shutdown backend")

	// Update tooltip periodically
	go func() {
		for {
			time.Sleep(30 * time.Second)
			systray.SetTooltip(getTrayTooltip())
		}
	}()

	// Menu handlers
	go func() {
		for {
			select {
			case <-mDashboard.ClickedCh:
				_ = openBrowser("http://localhost:8082")
			case <-mStatus.ClickedCh:
				_ = openBrowser("http://localhost:8082/api/health")
			case <-mRestartDaemon.ClickedCh:
				StopDaemon()
				StartDaemon()
			case <-mRestartWorker.ClickedCh:
				StopWorker()
				StartWorker()
			case <-mQuit.ClickedCh:
				systray.Quit()
				os.Exit(0)
			}
		}
	}()
}

func onTrayExit() {
	// Cleanup (systray handles it)
}

func getTrayTooltip() string {
	var s models.KeeperSettings
	if err := db.DB.First(&s, "id = ?", "default").Error; err != nil {
		return "Jules Autopilot"
	}
	var sessionCount int64
	db.DB.Model(&models.JulesSession{}).Count(&sessionCount)

	var queueCount int64
	db.DB.Model(&models.QueueJob{}).Where("status IN ?", []string{"pending", "processing"}).Count(&queueCount)

	daemon := "off"
	if GetDaemon().IsRunning() {
		daemon = "on"
	}

	return fmt.Sprintf("Jules Autopilot - Daemon:%s Sessions:%d Queue:%d", daemon, sessionCount, queueCount)
}

func openBrowser(url string) error {
	switch runtime.GOOS {
	case "windows":
		return exec.Command("rundll32", "url.dll,FileProtocolHandler", url).Start()
	case "darwin":
		return exec.Command("open", url).Start()
	default:
		return exec.Command("xdg-open", url).Start()
	}
}
