import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getSession } from '@/lib/session';
import { handleInternalError } from '@/lib/api/error';

/**
 * POST /api/swarms/scale
 * 
 * Dynamically scales an agent swarm by adding or removing tasks.
 * Used for one-click agent scaling from the dashboard.
 */
export async function POST(req: Request) {
    try {
        const session = await getSession();
        if (!session?.workspaceId) {
            return new NextResponse('Unauthorized', { status: 401 });
        }

        const body = await req.json();
        const { swarmId, targetSize } = body;

        if (!swarmId || typeof targetSize !== 'number' || targetSize < 1) {
            return NextResponse.json(
                { error: 'swarmId (string) and targetSize (number >= 1) are required' },
                { status: 400 }
            );
        }

        // Get current swarm
        const swarm = await prisma.agentSwarm.findUnique({
            where: { id: swarmId },
            include: { tasks: true }
        });

        if (!swarm) {
            return NextResponse.json({ error: 'Swarm not found' }, { status: 404 });
        }

        const currentSize = swarm.tasks.length;
        const delta = targetSize - currentSize;

        if (delta > 0) {
            // Scale UP — add new pending tasks
            const newTasks = Array.from({ length: delta }, (_, i) => ({
                swarmId,
                title: `Scaled task ${currentSize + i + 1}`,
                prompt: `Auto-generated by scale-up from ${currentSize} to ${targetSize}`,
                description: `Auto-generated by scale-up from ${currentSize} to ${targetSize}`,
                status: 'pending' as const,
                priority: 0,
                assignedModel: 'gpt-4o-mini'
            }));

            await prisma.swarmTask.createMany({ data: newTasks });
        } else if (delta < 0) {
            // Scale DOWN — remove pending tasks (never remove running/completed)
            const pendingTasks = swarm.tasks
                .filter(t => t.status === 'pending')
                .slice(0, Math.abs(delta));

            if (pendingTasks.length > 0) {
                await prisma.swarmTask.deleteMany({
                    where: { id: { in: pendingTasks.map(t => t.id) } }
                });
            }
        }

        // Get updated state
        const updatedSwarm = await prisma.agentSwarm.findUnique({
            where: { id: swarmId },
            include: { tasks: { select: { id: true, status: true } } }
        });

        return NextResponse.json({
            swarmId,
            previousSize: currentSize,
            targetSize,
            actualSize: updatedSwarm?.tasks.length ?? currentSize,
            delta,
            action: delta > 0 ? 'scaled_up' : delta < 0 ? 'scaled_down' : 'no_change'
        });
    } catch (error) {
        return handleInternalError(req, error);
    }
}
